add SDK docs
OAK-Foundation/OAK-docs pull request #33
Opened 2022-05-03 14:37 UTC by justinzhou93

2022-05-03 14:39 UTC, justinzhou93 commented
worth spinning up locally and seeing how it looks 
![image](https://user-images.githubusercontent.com/22332240/166474647-78593c38-86b4-458d-b8e4-d0b15f389acb.png)

I put almost all of the documentation as comments with the function definitions, since they all live inside of a class function. It seemed more easily understandable this way, but lemme know this is too confusing.

2022-05-03 17:54 UTC, irsal requested changes
We definitely need cookbooks, or something like this https://polkadot.js.org/docs/api/cookbook/blocks

I'd go through the code snippet for building an hourly call with validation and error handling

2022-05-03 17:54 UTC, irsal commented on _docs/automation-time-js-sdk.md
> + * class. This is currently only limited to 24 instances. These timstamps do not
spelling: timestamps

2022-05-03 17:54 UTC, irsal commented on _docs/automation-time-js-sdk.md
> + * limited to up to 24 occurences per extrinsic call.
spelling: occurrences

2022-05-04 16:56 UTC, irsal approved these changes
so much better; a few non-blocking items to edit

2022-05-04 16:56 UTC, irsal commented on _docs/automation-time-js-sdk.md
> +This is the documentation for the Javascript SDK for the Time Trigger blockchain APIs. You can find the SDK here: https://github.com/OAK-Foundation/OAK-JS-SDK.
use mark down link notation `[](url)`

2022-05-04 16:56 UTC, irsal commented on _docs/automation-time-js-sdk.md
> +  const timestamps = recurrer.getHourlyRecurringTimestamps(Date.now(), 24)
Add a comment above this explaining what the intention is

2022-05-04 16:56 UTC, irsal commented on _docs/automation-time-js-sdk.md
> +  const providedID = uuid.v4()
add a comment recommending that this gets savedsomewhere

2022-05-04 18:47 UTC, merged